 name: myfirstAcnions
 on:
  push:
     branches:  
       - master
 jobs:
   build:
     runs-on: ubuntu-latest 
       # Plugin checkout
     steps:
       - uses: actions/checkout@v3
# java setup
       - uses: actions/setup-java@v3
         with:
           distribution: zulu
           java-version: 17
       - name: Run Tests
         run: mvn clean test
 # Копируем историю в папку allure-history.
       - name: Copy History
         uses: actions/checkout@v3
         if: always()
         with:
           ref: gh-pages
           path: gh-pages
# Строим отчет используя папку allure-history
       - name: Build report
         uses: simple-elf/allure-report-action@master
         if: always()
         with:
           gh_pages: gh-pages
           allure_results: build/allure-results
           allure_history: allure-history
 # Публикуем отчет
       - name: Publish report
         if: always()
         uses: peaceiris/actions-gh-pages@v2
         env:
            github_token: $
            # PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
